apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: blue
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: blue-containers
          image: 037037/mynginx:blue
          ports:
            - containerPort: 80
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: staging-service
spec:
  type: LoadBalancer
  selector:
    app: green
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 80